### ISSUE TITLE
Info riguardo modulo corrispettivi per v14

### ISSUE THREAD

**Issue by tgd1973** [SirTakobi/l10n-italy#29]
Buongiorno e scusi per intervento ma visto che lei stava lavorando al passaggio per la versione 14 del modulo `l10n_it_corrispettivi` , le vorrei chiedere quale sarà il futuro di  questo modulo , visto che attualmente i corrispettivi per la gran parte vengono comunicati in automatico dai registratori di cassa ? 
Io chiedo perche a me interessa per  un e-commerce, essendo unica applicazione a quale Agenzia li richiede ancora in formato manuale, addirittura cartaceo /Excel. Sarebbe molto utile se si potesse integrare nella contabilità Odoo per non dover più avere la necessita di un Excel.
In concreto per adesso si può scaricare da qualche parte una bozza del  `  l10n_it_corrispettivi   `  adatta per v14  ?

Grazie.

**Comment by SirTakobi** [comment]
Buongiorno, purtroppo non mi è arrivata nessuna notifica di questa issue e la vedo solo adesso per caso.
Per parlare dei moduli della localizzazione meglio scrivere in https://discord.com/invite/FeYcxprGdh o aprire una issue in https://github.com/OCA/l10n-italy/issues
